version: '3.8'
services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres_library_db
    restart: always
    environment:
      POSTGRES_USER: james09
      POSTGRES_PASSWORD: lib123
      POSTGRES_DB: library_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: